import { world, system } from "@minecraft/server"

export const itemsSetts = [
    { item: "undefined", rotPos: 0 },
    { item: "sea_lantern", rotPos: 0 },
    { item: "sword", rotPos: 1 },
    { item: "mace", rotPos: 1 },
    { item: "shovel", rotPos: 1 },
    { item: "pickaxe", rotPos: 1 },
    { item: "hoe", rotPos: 1 },
    { item: "_axe ", rotPos: 1 },
    { item: "e_rod", rotPos: 1 },
    { item: ":stick ", rotPos: 1 },
    { item: ":bamboo ", rotPos: 1 },
    { item: ":bone ", rotPos: 1 },

    { item: "chestplate", rotPos: 2 },
    { item: "boots", rotPos: 2 },
    { item: "helmet", rotPos: 2 },
    { item: "leggings", rotPos: 2 },
    { item: "ball", rotPos: 2 },
    { item: "bundle", rotPos: 2 },
    { item: "lead", rotPos: 2 },
    { item: "flint", rotPos: 2 },
    { item: "shears", rotPos: 2 },
    { item: "clock", rotPos: 2 },
    { item: "compass", rotPos: 2 },
    { item: "bread", rotPos: 2 },
    { item: "totem", rotPos: 2 },
    { item: "cook", rotPos: 2 },
    { item: "stew", rotPos: 2 },
    { item: "soup", rotPos: 2 },
    { item: "potato", rotPos: 2 },
    { item: "pie", rotPos: 2 },
    { item: "kelp ", rotPos: 2 },
    { item: "armor ", rotPos: 2 },
    { item: "cake", rotPos: 2 },
    { item: "charge", rotPos: 2 },
    { item: "coal ", rotPos: 2 },
    { item: "horn ", rotPos: 2 },
    { item: "horn_coral ", rotPos: 2 },
    { item: "map", rotPos: 2 },
    { item: "saddle", rotPos: 2 },
    { item: "harness", rotPos: 2 },
    { item: "elytra", rotPos: 2 },
    { item: "bottle", rotPos: 2 },
    { item: "potion", rotPos: 2 },
    { item: "brush", rotPos: 2 },
    { item: "_door", rotPos: 2 },
    { item: "ladder", rotPos: 2 },
    { item: "_bars", rotPos: 2 },
    { item: "cauldron", rotPos: 2 },
    { item: "torch", rotPos: 2 },
    { item: "sea_pickle", rotPos: 2 },
    { item: "lantern", rotPos: 2 },
    { item: "candle", rotPos: 2 },
    { item: "campfire", rotPos: 2 },
    { item: "_stand", rotPos: 2 },
    { item: "bed ", rotPos: 2 },
    { item: "disc", rotPos: 2 },
    { item: "dust", rotPos: 2 },
    { item: "_sign", rotPos: 2 },
    { item: "painting", rotPos: 2 },
    { item: ":frame", rotPos: 2 },
    { item: "w_frame", rotPos: 2 },
    { item: "flower_pot", rotPos: 2 },
    { item: "bowl", rotPos: 2 },
    { item: "bucket", rotPos: 2 },
    { item: "bell", rotPos: 2 },
    { item: "scute", rotPos: 2 },
    { item: ":diamond ", rotPos: 2 },
    { item: "_nugget", rotPos: 2 },
    { item: "raw_copper ", rotPos: 2 },
    { item: "raw_gold ", rotPos: 2 },
    { item: "raw_iron ", rotPos: 2 },
    { item: "_ingot", rotPos: 2 },
    { item: ":emerald ", rotPos: 2 },
    { item: ":quartz ", rotPos: 2 },
    { item: "_membrane", rotPos: 2 },
    { item: ":brick ", rotPos: 2 },
    { item: "resin_brick ", rotPos: 2 },
    { item: ":netherbrick ", rotPos: 2 },
    { item: "_shard", rotPos: 2 },
    { item: "_crystal", rotPos: 2 },
    { item: "_shell", rotPos: 2 },
    { item: "heart_of_the_sea", rotPos: 2 },
    { item: "_scrap", rotPos: 2 },
    { item: "leather ", rotPos: 2 },
    { item: "string", rotPos: 2 },
    { item: "gunpowder", rotPos: 2 },
    { item: "feather", rotPos: 2 },
    { item: "eye", rotPos: 2 },
    { item: "dragon_breath", rotPos: 2 },
    { item: "_tear", rotPos: 2 },
    { item: "redstone ", rotPos: 2 },
    { item: "lever", rotPos: 2 },
    { item: "_pearl", rotPos: 2 },
    { item: "_star", rotPos: 2 },
    { item: "rocket", rotPos: 2 },
    { item: "paper", rotPos: 2 },
    { item: "book ", rotPos: 2 },
    { item: "_cream", rotPos: 2 },
    { item: "_foot", rotPos: 2 },
    { item: "_hide", rotPos: 2 },
    { item: "_hook", rotPos: 2 },
    { item: "blaze_powder", rotPos: 2 },
    { item: "boat", rotPos: 2 },
    { item: "_raft", rotPos: 2 },
    { item: "rail", rotPos: 2 },
    { item: "minecart", rotPos: 2 },
    { item: "_template", rotPos: 2 },
    { item: "name_tag", rotPos: 2 },
    { item: "hopper", rotPos: 2 },
    { item: "repeater", rotPos: 2 },
    { item: "comparator", rotPos: 2 },
    { item: "_chain", rotPos: 2 },
    { item: "_pattern", rotPos: 2 },
    { item: "_sherd", rotPos: 2 },
    { item: "apple", rotPos: 2 },
    { item: "carrot ", rotPos: 2 },
    { item: "beetroot", rotPos: 2 },
    { item: "wheat", rotPos: 2 },
    { item: "_seeds", rotPos: 2 },
    { item: "_pod", rotPos: 2 },
    { item: "_sapling", rotPos: 2 },
    { item: "_key", rotPos: 2 },
    { item: "lily", rotPos: 2 },
    { item: "sunflower", rotPos: 2 },
    { item: "_slice", rotPos: 2 },
    { item: "_berries", rotPos: 2 },
    { item: "honeycomb ", rotPos: 2 },
    { item: "_clump", rotPos: 2 },
    { item: "fern", rotPos: 2 },
    { item: "grass ", rotPos: 2 },
    { item: "bush", rotPos: 2 },
    { item: "_sprouts", rotPos: 2 },
    { item: "coral ", rotPos: 2 },
    { item: "coral_fan ", rotPos: 2 },
    { item: "n_roots", rotPos: 2 },
    { item: "g_roots", rotPos: 2 },
    { item: "d_roots", rotPos: 2 },
    { item: "cornflower", rotPos: 2 },
    { item: "_tulip", rotPos: 2 },
    { item: "_bluet", rotPos: 2 },
    { item: "allium", rotPos: 2 },
    { item: "_orchid", rotPos: 2 },
    { item: "poppy", rotPos: 2 },
    { item: "dandelion", rotPos: 2 },
    { item: "pitcher", rotPos: 2 },
    { item: "peony", rotPos: 2 },
    { item: "_rose", rotPos: 2 },
    { item: "lilac", rotPos: 2 },
    { item: "lapis_lazuli", rotPos: 2 },
    { item: "_dye", rotPos: 2 },
    { item: "flowers", rotPos: 2 },
    { item: "_petals", rotPos: 2 },
    { item: "_sac", rotPos: 2 },
    { item: "_cluster", rotPos: 2 },
    { item: "vine", rotPos: 2 },
    { item: "bone_meal", rotPos: 2 },
    { item: "cactus_flower", rotPos: 2 },
    { item: "_beans", rotPos: 2 },
    { item: "_litter", rotPos: 2 },
    { item: "hanging_moss", rotPos: 2 },
    { item: "_lichen", rotPos: 2 },
    { item: "cod ", rotPos: 2 },
    { item: "rabbit ", rotPos: 2 },
    { item: "mutton", rotPos: 2 },
    { item: "beef", rotPos: 2 },
    { item: "porkchop", rotPos: 2 },
    { item: "chicken ", rotPos: 2 },
    { item: "salmon ", rotPos: 2 },
    { item: "propagule", rotPos: 2 },
    { item: "_fish ", rotPos: 2 },
    { item: "pufferfish", rotPos: 2 },
    { item: "_fungus ", rotPos: 2 },
    { item: "mushroom ", rotPos: 2 },
    { item: "dragon_egg", rotPos: 16, stackOffset: 2 },
    { item: ":egg ", rotPos: 2 },
    { item: "_egg ", rotPos: 2 },
    { item: "sugar", rotPos: 2 },
    { item: "_flesh", rotPos: 2 },
    { item: "web", rotPos: 2 },
    { item: "g_spawn", rotPos: 2 },
    { item: "_wart ", rotPos: 2 },
    { item: "chorus_fruit", rotPos: 2 },
    { item: "_bud", rotPos: 2 },
    { item: "_vein", rotPos: 2 },

    { item: "arrow", rotPos: 3 },
    { item: "shield", rotPos: 5 },
    { item: ":bow ", rotPos: 4 },
    { item: "trident", rotPos: 6 },
    { item: "spear", rotPos: 7 },
    { item: "crossbow", rotPos: 8 },
    { item: "pointed_dripstone", rotPos: 9 },
    { item: "spyglass", rotPos: 9 },
    { item: "a_stick", rotPos: 10 },
    { item: "fishing_rod", rotPos: 10 },
    { item: "d_rod", rotPos: 11 },
    { item: "lightning_rod", rotPos: 11 },
    { item: "_wall", rotPos: 12, stackOffset: 1 },
    { item: "pane", rotPos: 13 },
    { item: "pale_oak_fence_gate", rotPos: 24 },
    { item: "fence", rotPos: 13 },
    { item: "dried_ghast", rotPos: 14 },
    { item: "_stairs", rotPos: 14 },
    { item: "chorus_flower", rotPos: 14, stackOffset: 1 },

    { item: "scaffolding", rotPos: 15, stackOffset: 2 },
    { item: "_layer", rotPos: 15 },
    { item: "azalea ", rotPos: 15, stackOffset: 2 },
    { item: "_dripleaf", rotPos: 15 },
    { item: "_blossom", rotPos: 15 },
    { item: "stonecutter", rotPos: 15, stackOffset: 1 },
    { item: "decorated_pot", rotPos: 15, stackOffset: 2 },
    { item: "_plate", rotPos: 15, stackOffset: 1 },
    { item: "_detector", rotPos: 15, stackOffset: 2 },
    { item: "_button", rotPos: 19 },
    { item: "trapdoor", rotPos: 15 },
    { item: "_slab", rotPos: 15, stackOffset: 2 },
    { item: "_carpet", rotPos: 15, stackOffset: 2 },
    { item: "enchanting_table", rotPos: 15, stackOffset: 2 },
    { item: "grindstone", rotPos: 15, stackOffset: 2 },
    { item: "portal", rotPos: 15, stackOffset: 2 },
    { item: "sculk_sensor", rotPos: 15 },

    { item: "anvil", rotPos: 16, stackOffset: 1 },
    { item: "chiseled_bookshelf", rotPos: 17, stackOffset: 1 },
    { item: "furnace", rotPos: 17 },
    { item: "smoker", rotPos: 17 },
    { item: "crafter", rotPos: 17, stackOffset: 1 },
    { item: "loom", rotPos: 17, stackOffset: 1 },
    { item: "dropper", rotPos: 17, stackOffset: 1 },
    { item: "dispenser", rotPos: 17, stackOffset: 1 },
    { item: "observer", rotPos: 17, stackOffset: 1 },
    { item: "lectern", rotPos: 17, stackOffset: 1 },
    { item: "beehive", rotPos: 17 },
    { item: "bee_nest", rotPos: 17, stackOffset: 1 },

    { item: "chest ", rotPos: 18, stackOffset: 2 },
    { item: "_core", rotPos: 19, stackOffset: 2 },
    { item: "_shelf", rotPos: 19, stackOffset: 1 },
    { item: "statue", rotPos: 20 },
    { item: "_head", rotPos: 21, stackOffset: 1 },
    { item: "skull", rotPos: 21, stackOffset: 1 },
    { item: "conduit", rotPos: 21 },
    { item: "banner ", rotPos: 22 },
    { item: "carved_pumpkin ", rotPos: 23, stackOffset: 1 },
]